services:
  # Backend API Service
  - type: web
    name: shoponthefly-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-app.netlify.app
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
      - key: DATABASE_URL
        fromDatabase:
          name: shoponthefly-db
          property: connectionString

databases:
  # PostgreSQL Database
  - name: shoponthefly-db
    databaseName: shoponthefly
    user: shoponthefly_user
    plan: free 